### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by jeongjunjjkim** [glaserlab/sca#6]
Trying out the example notebooks here - is the code base meant to support GPU-based optimization (via torch library)? If so, what are the install instructions?

**Comment by jglaser2** [comment]
At the moment, we have basic support for GPU optimization (when using cuda) that should occur automatically, but we haven't tested this extensively.

This gets implemented in models.py line 540:
`device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")`

**Comment by yaxigeigei** [comment]
Hi, I encountered the following error when using GPU. Do you have any insight?
`File c:\users\many\oconnorlab dropbox\duo xu\documents\rnd\chang lab\project_np\code\third_party_python\sca\sca\loss_funcs.py:58 in my_loss_norm
    loss = torch.sum((sample_weight*(output - target))**2) + lam_sparse*torch.sum(torch.abs(latent)) + lam_orthog*torch.norm(V.T@V-torch.eye(V.shape[1]))**2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

Here is my GPU info
CUDA version: 11.8
Is CUDA available: True
Current CUDA device: 0
CUDA device name: NVIDIA GeForce RTX 3060 Ti

**Comment by yaxigeigei** [comment]
> Hi, I encountered the following error when using GPU. Do you have any insight?
> 
> ```
> File \sca\loss_funcs.py:58 in my_loss_norm
>     loss = torch.sum((sample_weight*(output - target))**2) + lam_sparse*torch.sum(torch.abs(latent)) + lam_orthog*torch.norm(V.T@V-torch.eye(V.shape[1]))**2
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> ```
> 
> Here is my GPU info CUDA version: 11.8 Is CUDA available: True Current CUDA device: 0 CUDA device name: NVIDIA GeForce RTX 3060 Ti

I resolved the above issue by specifying the default device to this GPU using torch.set_default_device.
Then I ran into the following error:
```
  File c:\users\many\oconnorlab dropbox\duo xu\documents\rnd\chang lab\project_np\code\third_party_python\sca\sca\models.py:597 in fit_transform
    self.params['U']=model.fc1.weight.detach().numpy().T

  File ~\anaconda3\envs\rsa\lib\site-packages\torch\utils\_device.py:62 in __torch_function__
    return func(*args, **kwargs)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

**Comment by jglaser2** [comment]
Thanks for pointing out these gpu issues - I'll take a closer look in the couple days.

For the most recent issue, I think you can follow the suggestion in the error. 
Something like:
    self.params['U']=Tensor.cpu(model.fc1.weight).detach().numpy().T

**Comment by yaxigeigei** [comment]
> Thanks for pointing out these gpu issues - I'll take a closer look in the couple days.
> 
> For the most recent issue, I think you can follow the suggestion in the error. Something like: self.params['U']=Tensor.cpu(model.fc1.weight).detach().numpy().T

Thanks for the prompt response! Yes, I have fixed them by adding .cpu() after .detach() and everything seems running correctly.

**Comment by jglaser2** [comment]
Great. I've made these updates within the pushed code. If other issues arise, please let me know.
